"""Authoritative story and hazards; geometry is authored in architecture.py."""
import json
from pathlib import Path
from architecture import apply_architecture
root=Path(__file__).resolve().parents[1]
rows=[{'name': 'RUSTED HARBOR',
  'subtitle': '01 / SHIPYARD GATE',
  'width': 3600,
  'vehicleX': 2450,
  'brief1': 'DENIZ: Efe, I have your signal. The shipyard gates are locked. I am coming.',
  'brief2': 'MIRA: The Iron Grid hijacked every work machine. Rescue the workers and shut down the crane core.',
  'radio': 'EFE: Catch the train... Commands are coming from the northern foundry.',
  'ending': 'The crane is down. Efe is alive. Cross the marsh to reach the northern rail line.',
  'bossName': 'CLAW CRANE',
  'hazards': []},
 {'name': 'TOXIC MARSH',
  'subtitle': '02 / NORTH MARSH',
  'width': 3840,
  'vehicleX': 2570,
  'brief1': 'MIRA: The marsh pipes are poisoning the sea. Efe hid the train route here.',
  'brief2': 'DENIZ: I will get the workers out. Then we break the dredger pump.',
  'radio': 'EFE: The Grid is copying human voices. Captain Sarp is listening to nobody.',
  'ending': 'The poison pump is broken. The shipment code can stop the armored train.',
  'bossName': 'ASH DREDGER',
  'hazards': [{'x': 740, 'y': 225, 'w': 80, 'h': 8, 'period': 3.8, 'on': 1.4, 'offset': 0, 'kind': 0},
              {'x': 1710, 'y': 225, 'w': 70, 'h': 8, 'period': 4.2, 'on': 1.4, 'offset': 1, 'kind': 0},
              {'x': 2840, 'y': 225, 'w': 76, 'h': 8, 'period': 3.6, 'on': 1.1, 'offset': 2, 'kind': 0}]},
 {'name': 'IRONLINE',
  'subtitle': '03 / MOUNTAIN FREIGHT',
  'width': 4000,
  'vehicleX': 2720,
  'brief1': 'DENIZ: I am aboard the moving freight. Every car carries another weapon.',
  'brief2': 'MIRA: The locomotive cannon seals the pass. Watch the gaps and cut the brake line.',
  'radio': 'EFE: There are no soldiers in the cargo. It is a city worth of power cores.',
  'ending': 'The train is stopped. The stolen cores are headed for the foundry. The Iron Grid is building an '
            'army.',
  'bossName': 'BLACK LOCOMOTIVE',
  'hazards': []},
 {'name': 'EMBER FOUNDRY',
  'subtitle': '04 / UNDER THE MOUNTAIN',
  'width': 3680,
  'vehicleX': 2430,
  'brief1': 'MIRA: The plant is critical. The presses are still running. Wait for the safe rhythm.',
  'brief2': 'DENIZ: Efe sabotaged the cores. The Grid trapped him below the tower. I will cool the furnace first.',
  'radio': 'SARP: One city can be spent for a coast. Deniz, turn back.',
  'ending': 'The giant furnace is cold. Sarp will launch from the storm tower. Efe is being held there.',
  'bossName': 'FORGE TITAN',
  'hazards': [{'x': 810, 'y': 184, 'w': 22, 'h': 48, 'period': 3.4, 'on': 1.1, 'offset': 0, 'kind': 1},
              {'x': 1480, 'y': 188, 'w': 22, 'h': 44, 'period': 3.8, 'on': 1.2, 'offset': 1, 'kind': 1},
              {'x': 2310, 'y': 180, 'w': 22, 'h': 52, 'period': 4.0, 'on': 1.4, 'offset': 0, 'kind': 1},
              {'x': 2770, 'y': 188, 'w': 22, 'h': 44, 'period': 3.4, 'on': 1.0, 'offset': 1.5, 'kind': 1}]},
 {'name': 'STORM RELAY',
  'subtitle': '05 / LAST RELAY',
  'width': 3840,
  'vehicleX': 2510,
  'brief1': 'EFE: Deniz! The relay can hear me. Cross the lightning and open the three tower caps.',
  'brief2': 'MIRA: Cut the signal to the sea net and the command platform will be exposed.',
  'radio': 'EFE: I am free. But Sarp took the backup command core to sea!',
  'ending': 'The tower is silent and Efe is safe. The final platform lights burn beyond the storm.',
  'bossName': 'FOUR POLES',
  'hazards': [{'x': 740, 'y': 184, 'w': 18, 'h': 48, 'period': 3.4, 'on': 1, 'offset': 0, 'kind': 2},
              {'x': 1350, 'y': 184, 'w': 18, 'h': 48, 'period': 3.4, 'on': 1, 'offset': 1, 'kind': 2},
              {'x': 2010, 'y': 184, 'w': 18, 'h': 48, 'period': 3.4, 'on': 1, 'offset': 2, 'kind': 2},
              {'x': 2900, 'y': 144, 'w': 18, 'h': 44, 'period': 3.4, 'on': 0.8, 'offset': 0, 'kind': 2}]},
 {'name': 'FINAL WAVE',
  'subtitle': '06 / COMMAND PLATFORM',
  'width': 4200,
  'vehicleX': 2790,
  'brief1': 'EFE: The Iron Grid core is in Captain Sarp armor. Fire when it opens.',
  'brief2': 'DENIZ: The whole coast can hear us. We get the workers out, then end this war.',
  'radio': 'MIRA: Evac ships are ready. There is no retreat now.',
  'ending': 'The Iron Grid is silent. The coast belongs to its people again. Deniz and Efe sail home.',
  'bossName': 'IRON GRID / SARP',
  'hazards': [{'x': 790, 'y': 196, 'w': 22, 'h': 36, 'period': 4, 'on': 1.2, 'offset': 0, 'kind': 1},
              {'x': 2110, 'y': 190, 'w': 18, 'h': 42, 'period': 3.8, 'on': 1.2, 'offset': 1, 'kind': 2},
              {'x': 3230, 'y': 190, 'w': 22, 'h': 42, 'period': 4, 'on': 1.2, 'offset': 1, 'kind': 1}]}]
levels=[dict(r,theme=i,bossKind=i) for i,r in enumerate(rows)]
apply_architecture(levels)
(root/'data/campaign.json').write_text(json.dumps({'title':'Iron Coast: Scrap Tide','version':2,'levels':levels},ensure_ascii=False,indent=2)+'\n')
print('Authored',len(levels),'architectural missions')
