// Generated by tools/compile_presentation.py. Edit data/presentation.json only.
#pragma once
#include <array>
#include <cstdint>
namespace kh::tuning {
struct Lighting {
  float key;
  float fill;
  float rim;
  float exposure;
  float bloom;
  float shaft;
  float shaftStep;
  float shaftSpread;
  float shaftNoise;
  float shaftSpeed;
  float ao;
  float aoWidth;
  float fogSpeed;
  float fogHeight;
  float fogSpacing;
  float dof;
  float motionBlur;
  float grade;
  float focusParallax;
};
inline constexpr Lighting lighting = {0.8f, 0.66f, 0.23f, 1.18f, 0.65f, 0.7f, 6.0f, 0.28f, 0.22f, 0.8f, 0.28f, 9.0f, 4.0f, 40.0f, 175.0f, 1.15f, 0.65f, 0.035f, 0.18f};
struct Combat {
  float headThreshold;
  float legThreshold;
  float headFlinch;
  float torsoFlinch;
  float legFlinch;
  float headAngle;
  float torsoAngle;
  float legSquash;
  float knockback;
  float hitStop;
  float heavyHitStop;
  float hitCooldown;
  float hitShake;
  float deathDuration;
  float deathTravel;
  float deathLift;
  float deathAngle;
  float impactParticles;
  float impactLife;
  float impactSpeed;
  uint32_t hitColor;
  uint32_t bloodColor;
  uint32_t dustColor;
};
inline constexpr Combat combat = {0.26f, 0.73f, 0.19f, 0.13f, 0.23f, 12.0f, 7.0f, 0.12f, 6.0f, 0.025f, 0.045f, 0.12f, 0.65f, 0.65f, 17.0f, 12.0f, 58.0f, 7.0f, 0.24f, 75.0f, 0xFFB19AFFu, 0xBA655EFFu, 0xB2BFC6FFu};
struct Audio {
  float falloff;
  float distantLowpass;
  float musicGain;
  float duck;
  float attack;
  float release;
  float tail;
  float tailDelay;
  float emptyDuration;
  float emptyGain;
  float reloadGain;
  float impactGain;
  float discoveryGain;
  float reloadLatch;
  float reloadClose;
  float clickDecay;
  float impactDecay;
  float crackDecay;
  float tailDecay;
  float tailGain;
  float flamePulse;
  float flameDecay;
  float discoveryFrequency;
  float discoveryPitchRise;
  float discoveryDuration;
};
inline constexpr Audio audio = {230.0f, 0.08f, 0.7f, 0.7f, 0.0015f, 0.025f, 0.16f, 0.025f, 0.075f, 0.12f, 0.15f, 0.19f, 0.15f, 0.55f, 0.88f, 65.0f, 35.0f, 180.0f, 11.0f, 0.18f, 72.0f, 4.0f, 660.0f, 660.0f, 0.6f};
struct Maps {
  uint32_t keyColor;
  uint32_t fillColor;
  uint32_t fogColor;
  uint32_t edgeColor;
  uint32_t skyColor;
  float fogDensity;
  float fogDrift;
  float textureGain;
  float alcoveLampX;
  float alcoveLampY;
};
inline constexpr std::array<Maps, 6> maps = {{{0x8FBFCBFFu, 0xFFD09AFFu, 0x244355FFu, 0x73989EFFu, 0x102333FFu, 0.08f, 1.0f, 0.85f, 0.18f, 0.22f},
{0xB9CDB0FFu, 0xDADEA5FFu, 0x536C61FFu, 0xA1B09AFFu, 0x182E2AFFu, 0.15f, 0.6f, 0.88f, 0.74f, 0.17f},
{0x95BDDCFFu, 0xF1B67EFFu, 0x354C65FFu, 0x9BADBEFFu, 0x172537FFu, 0.065f, 1.5f, 0.87f, 0.86f, 0.25f},
{0xFFA371FFu, 0xFFD4A3FFu, 0x78534AFFu, 0xC6A282FFu, 0x301E22FFu, 0.1f, 0.7f, 0.95f, 0.16f, 0.18f},
{0x9DCEEDFFu, 0xC4E9FFFFu, 0x677D98FFu, 0xCADCE6FFu, 0x1A2B42FFu, 0.13f, 1.2f, 0.96f, 0.85f, 0.16f},
{0x8BCCC3FFu, 0xED856CFFu, 0x395850FFu, 0x8FADA7FFu, 0x102E2DFFu, 0.07f, 0.4f, 0.82f, 0.9f, 0.14f}}};
struct Weapons {
  uint32_t flashColor;
  uint32_t tracerColor;
  float flashLength;
  float flashWidth;
  float flashDuration;
  float tracerLength;
  float recoil;
  float casing;
  float casingLife;
  float casingSpeed;
  float magazine;
  float reload;
  float fireDuration;
  float frequency;
  float pitchDrop;
  float noise;
  float lowpass;
  float gain;
  float decay;
  float reloadPitch;
  float impactSize;
};
inline constexpr std::array<Weapons, 6> weapons = {{{0xFFF1B4FFu, 0xFFE7A8FFu, 9.0f, 3.0f, 0.05f, 7.0f, 1.2f, 1.0f, 0.48f, 48.0f, 12.0f, 0.72f, 0.14f, 175.0f, -600.0f, 0.72f, 0.65f, 0.32f, 28.0f, 800.0f, 2.0f},
{0xFFBF62FFu, 0xFFBE6CFFu, 14.0f, 4.0f, 0.045f, 11.0f, 1.9f, 1.0f, 0.48f, 48.0f, 30.0f, 1.15f, 0.16f, 110.0f, -320.0f, 0.65f, 0.48f, 0.34f, 23.0f, 500.0f, 2.5f},
{0xFFE3A0FFu, 0xFFF2CDFFu, 19.0f, 8.0f, 0.085f, 4.0f, 4.0f, 2.0f, 0.48f, 48.0f, 6.0f, 1.25f, 0.32f, 65.0f, -120.0f, 0.85f, 0.3f, 0.48f, 14.0f, 320.0f, 3.0f},
{0xF79455FFu, 0xED995EFFu, 17.0f, 7.0f, 0.11f, 12.0f, 4.8f, 0.0f, 0.48f, 48.0f, 1.0f, 1.3f, 0.42f, 48.0f, 45.0f, 0.8f, 0.13f, 0.4f, 8.0f, 170.0f, 5.0f},
{0xFF783EFFu, 0xFF934BFFu, 14.0f, 9.0f, 0.1f, 13.0f, 1.0f, 0.0f, 0.48f, 48.0f, 24.0f, 0.95f, 0.27f, 72.0f, 80.0f, 0.94f, 0.18f, 0.28f, 3.0f, 110.0f, 4.0f},
{0x81F3FFFFu, 0x70E7FFFFu, 22.0f, 2.0f, 0.075f, 24.0f, 0.6f, 0.0f, 0.48f, 48.0f, 8.0f, 0.85f, 0.25f, 950.0f, -2100.0f, 0.045f, 0.6f, 0.27f, 17.0f, 610.0f, 2.0f}}};
struct Secrets {
  float map;
  float x;
  float y;
  float radius;
  float kind;
};
inline constexpr std::array<Secrets, 2> secrets = {{{0.0f, 1380.0f, -50.04978038067355f, 27.0f, 0.0f},
{4.0f, 800.0f, -96.0f, 27.0f, 1.0f}}};
struct Discovery {
  float duration;
  float score;
  float plaqueWidth;
  float plaqueHeight;
  float flagWidth;
  float flagHeight;
  uint32_t color;
};
inline constexpr Discovery discovery = {3.0f, 250.0f, 22.0f, 9.0f, 20.0f, 13.0f, 0xEDD9A4FFu};
struct Environment {
  float fanSpeed;
  float terminalBlink;
  float fogWaveSpeed;
  float windowShaftSlant;
  float shaftRadiance;
  float sourceBloomRadius;
  float sourceBloomHeight;
  float skyDofAlpha;
  float motionAlpha;
  float alcoveSize;
  float alcoveSpacing;
  float alcoveGain;
  float alcoveLampRadius;
  float alcoveLampStrength;
};
inline constexpr Environment environment = {0.9f, 2.0f, 0.19f, 0.32f, 24.0f, 22.0f, 10.0f, 44.0f, 25.0f, 56.0f, 108.0f, 0.84f, 55.0f, 0.36f};
struct Materials {
  uint32_t color75876AFF;
  uint32_t color4B675AFF;
  uint32_t color7C9DB3FF;
  uint32_t color0A1522FF;
  uint32_t color687263FF;
  uint32_t color172A28FF;
  uint32_t colorAFBEC7FF;
  uint32_t color120C15FF;
  uint32_t colorC48A5588;
  uint32_t colorC9D9DFFF;
  uint32_t color294255FF;
  uint32_t color304F51FF;
  uint32_t color0A2024FF;
  uint32_t color36434AFF;
  uint32_t colorADA793FF;
  uint32_t color722B33FF;
  uint32_t color091822FF;
};
inline constexpr Materials materials = {0x75876AFFu, 0x4B675AFFu, 0x7C9DB3FFu, 0x0A1522FFu, 0x687263FFu, 0x172A28FFu, 0xAFBEC7FFu, 0x120C15FFu, 0xC48A5588u, 0xC9D9DFFFu, 0x294255FFu, 0x304F51FFu, 0x0A2024FFu, 0x36434AFFu, 0xADA793FFu, 0x722B33FFu, 0x091822FFu};
struct Camera {
  float anchorX;
  float lookAhead;
  float followSpeed;
  float verticalSpeed;
  float climbLook;
  float bossIntroDuration;
  float bossLift;
  float bossZoom;
  float climbZoom;
  float zoomSpeed;
};
inline constexpr Camera camera = {155.0f, 32.0f, 5.5f, 5.0f, 18.0f, 1.8f, 9.0f, 1.025f, 1.012f, 2.8f};
struct Surface {
  float sampleStep;
  float wallIntensity;
  float floorIntensity;
  float specularIntensity;
  float wallRadius;
  float reflectionHeight;
  float lightReach;
};
inline constexpr Surface surface = {12.0f, 28.0f, 85.0f, 115.0f, 0.8f, 6.0f, 1.65f};
struct SurfaceMaterials {
  float diffuse;
  float specular;
  float roughness;
};
inline constexpr std::array<SurfaceMaterials, 3> surfaceMaterials = {{{0.85f, 0.12f, 0.9f},
{0.58f, 0.85f, 0.25f},
{0.68f, 0.06f, 1.0f}}};
struct Hud {
  float healthDuration;
  float weaponDuration;
  float fadeDuration;
  float opacity;
  float margin;
  uint32_t healthColor;
  uint32_t weaponColor;
};
inline constexpr Hud hud = {2.4f, 1.4f, 0.5f, 0.8f, 14.0f, 0xD58F73FFu, 0xCDC6B3FFu};
struct HarborScene {
  float width;
  float sourceFloor;
  float sourceAspect;
};
inline constexpr HarborScene harborScene = {720.0f, 0.658f, 1.7768331562167907f};
struct HarborLights {
  float x;
  float y;
  float radius;
  float strength;
  uint32_t color;
};
inline constexpr std::array<HarborLights, 6> harborLights = {{{73.0f, 8.0f, 85.0f, 0.5f, 0xE5A66CFFu},
{117.0f, 106.0f, 95.0f, 0.6f, 0xF9BA7AFFu},
{278.0f, 145.0f, 95.0f, 0.6f, 0xEDB886FFu},
{452.0f, 198.0f, 78.0f, 0.5f, 0xFFC07EFFu},
{501.0f, 173.0f, 70.0f, 0.5f, 0x96C77AFFu},
{664.0f, 189.0f, 92.0f, 0.5f, 0x99CFDCFFu}}};
struct ScenePlates {
  float sourceFloor;
  float sourceAspect;
};
inline constexpr std::array<ScenePlates, 6> scenePlates = {{{0.704f, 3.0f},
{0.69f, 3.0f},
{0.707f, 3.0f},
{0.707f, 3.0f},
{0.74f, 2.998618784530387f},
{0.727f, 3.0f}}};
struct SceneLights {
  float map;
  float x;
  float y;
  float radius;
  float strength;
  float window;
  float flicker;
  float rate;
  uint32_t color;
};
inline constexpr std::array<SceneLights, 25> sceneLights = {{{0.0f, 805.0f, 12.0f, 95.0f, 0.36f, 0.0f, 0.035f, 1.4f, 0xFFD09AFFu},
{0.0f, 1065.0f, 102.0f, 115.0f, 0.36f, 0.0f, 0.035f, 1.77f, 0xFFD09AFFu},
{0.0f, 1300.0f, 160.0f, 125.0f, 0.36f, 1.0f, 0.035f, 2.1399999999999997f, 0x8FBFCBFFu},
{0.0f, 1610.0f, 120.0f, 120.0f, 0.36f, 0.0f, 0.035f, 2.51f, 0xFFD09AFFu},
{0.0f, 1840.0f, 75.0f, 130.0f, 0.36f, 0.0f, 0.035f, 2.88f, 0xFFD09AFFu},
{1.0f, 160.0f, 50.0f, 110.0f, 0.36f, 0.0f, 0.035f, 1.4f, 0xDADEA5FFu},
{1.0f, 530.0f, 84.0f, 150.0f, 0.36f, 1.0f, 0.035f, 1.77f, 0xB9CDB0FFu},
{1.0f, 840.0f, 168.0f, 100.0f, 0.36f, 0.0f, 0.035f, 2.1399999999999997f, 0xDADEA5FFu},
{1.0f, 1230.0f, 98.0f, 145.0f, 0.36f, 0.0f, 0.035f, 2.51f, 0xDADEA5FFu},
{2.0f, 150.0f, 153.0f, 105.0f, 0.36f, 0.0f, 0.035f, 1.4f, 0xF1B67EFFu},
{2.0f, 550.0f, 162.0f, 125.0f, 0.36f, 0.0f, 0.035f, 1.77f, 0xF1B67EFFu},
{2.0f, 1040.0f, 110.0f, 130.0f, 0.36f, 1.0f, 0.035f, 2.1399999999999997f, 0x95BDDCFFu},
{2.0f, 1530.0f, 145.0f, 130.0f, 0.36f, 0.0f, 0.035f, 2.51f, 0xF1B67EFFu},
{3.0f, 140.0f, 90.0f, 145.0f, 0.36f, 0.0f, 0.035f, 1.4f, 0xFFD4A3FFu},
{3.0f, 630.0f, 40.0f, 130.0f, 0.36f, 0.0f, 0.035f, 1.77f, 0xFFD4A3FFu},
{3.0f, 980.0f, 167.0f, 115.0f, 0.36f, 0.0f, 0.035f, 2.1399999999999997f, 0xFFD4A3FFu},
{3.0f, 1370.0f, 105.0f, 165.0f, 0.36f, 0.0f, 0.035f, 2.51f, 0xFFD4A3FFu},
{4.0f, 125.0f, -30.0f, 150.0f, 0.36f, 1.0f, 0.035f, 1.4f, 0x9DCEEDFFu},
{4.0f, 655.0f, -80.0f, 170.0f, 0.36f, 1.0f, 0.035f, 1.77f, 0x9DCEEDFFu},
{4.0f, 1100.0f, 45.0f, 130.0f, 0.36f, 0.0f, 0.035f, 2.1399999999999997f, 0xC4E9FFFFu},
{4.0f, 1510.0f, 120.0f, 130.0f, 0.36f, 0.0f, 0.035f, 2.51f, 0xC4E9FFFFu},
{5.0f, 200.0f, 44.0f, 125.0f, 0.36f, 1.0f, 0.035f, 1.4f, 0x8BCCC3FFu},
{5.0f, 690.0f, 157.0f, 90.0f, 0.36f, 0.0f, 0.035f, 1.77f, 0xED856CFFu},
{5.0f, 1020.0f, 83.0f, 145.0f, 0.36f, 0.0f, 0.035f, 2.1399999999999997f, 0xED856CFFu},
{5.0f, 1610.0f, 100.0f, 160.0f, 0.36f, 0.0f, 0.035f, 2.51f, 0xED856CFFu}}};
struct Effects {
  float explosionFrames;
  float explosionSize;
  float flameFps;
  float flameWidth;
  float flameHeight;
  float smokeOpacity;
  float enemyWalkFps;
  float reloadLean;
  float reloadDip;
};
inline constexpr Effects effects = {8.0f, 0.95f, 24.0f, 25.0f, 14.0f, 0.28f, 10.0f, 4.0f, 3.0f};
struct EnemyTypes {
  float speed;
  float standOff;
  float patrol;
  float windup;
  float recovery;
  float projectileSpeed;
  float bob;
  float strafe;
};
inline constexpr std::array<EnemyTypes, 5> enemyTypes = {{{34.0f, 150.0f, 120.0f, 0.48f, 0.85f, 115.0f, 0.0f, 0.0f},
{24.0f, 205.0f, 80.0f, 0.8f, 1.5f, 90.0f, 0.0f, 1.0f},
{21.0f, 60.0f, 130.0f, 0.65f, 1.1f, 105.0f, 0.0f, 0.0f},
{38.0f, 160.0f, 140.0f, 0.55f, 1.2f, 115.0f, 13.0f, 1.0f},
{0.0f, 0.0f, 0.0f, 0.9f, 1.6f, 145.0f, 0.0f, 0.0f}}};
struct GuardImpact {
  float sparkCount;
  float sparkLife;
  float sparkSpeed;
  float sparkGravity;
  float sparkTrailTime;
  float sparkTrailMax;
  uint32_t sparkColor;
  float landingPhase;
  float dustCount;
  float dustLife;
  float dustSpeed;
  float dustLift;
  float dustSize;
  float dustOpacity;
  uint32_t dustColor;
  float drag;
  float landingFrequency;
  float landingPitchDrop;
  float landingDuration;
  float landingGain;
  float landingNoise;
  float landingDecay;
};
inline constexpr GuardImpact guardImpact = {4.0f, 0.16f, 46.0f, 120.0f, 0.022f, 2.5f, 0xDEB985FFu, 0.62f, 5.0f, 0.32f, 18.0f, 7.0f, 3.5f, 24.0f, 0x87999EFFu, 6.0f, 92.0f, -135.0f, 0.18f, 0.19f, 0.15f, 22.0f};
struct GuardAction {
  float cellSize;
  float baseline;
  float renderSize;
  float strideLength;
  float attackDuration;
  float flashDuration;
  float lightRadius;
  float lightStrength;
  uint32_t lightColor;
};
inline constexpr GuardAction guardAction = {160.0f, 156.0f, 95.0f, 48.0f, 0.3f, 0.07f, 58.0f, 0.72f, 0xFFD09AFFu};
struct GuardPoseRoots {
  float x;
};
inline constexpr std::array<GuardPoseRoots, 16> guardPoseRoots = {{{81.5f},
{82.5f},
{79.0f},
{79.0f},
{79.0f},
{78.0f},
{79.0f},
{78.5f},
{89.0f},
{90.0f},
{90.0f},
{89.5f},
{90.5f},
{85.0f},
{88.5f},
{89.0f}}};
struct GuardFireAnchors {
  float x;
  float y;
  float end;
};
inline constexpr std::array<GuardFireAnchors, 4> guardFireAnchors = {{{53.0f, 76.0f, 0.035f},
{44.0f, 75.0f, 0.07f},
{42.0f, 75.5f, 0.16f},
{41.0f, 75.5f, 0.3f}}};
struct GuardReactions {
  float enabled;
  float cellSize;
  float baseline;
  float sourceScale;
  float renderSize;
  float headDuration;
  float torsoDuration;
  float legDuration;
  float flashDuration;
  float collapseDuration;
  float corpseHold;
  float fadeDuration;
  float hitTravel;
  float deathTravel;
};
inline constexpr GuardReactions guardReactions = {1.0f, 160.0f, 156.0f, 0.54f, 95.0f, 0.34f, 0.3f, 0.46f, 0.065f, 0.72f, 0.45f, 0.35f, 1.5f, 8.0f};
struct GuardHitTimeline {
  float frame;
  float end;
};
inline constexpr std::array<GuardHitTimeline, 12> guardHitTimeline = {{{1.0f, 0.2f},
{2.0f, 0.5f},
{0.0f, 0.78f},
{3.0f, 1.0f},
{5.0f, 0.2f},
{6.0f, 0.55f},
{4.0f, 0.8f},
{7.0f, 1.0f},
{9.0f, 0.2f},
{10.0f, 0.5f},
{9.0f, 0.78f},
{11.0f, 1.0f}}};
struct GuardDeathTimeline {
  float frame;
  float end;
};
inline constexpr std::array<GuardDeathTimeline, 8> guardDeathTimeline = {{{12.0f, 0.09f},
{13.0f, 0.2f},
{14.0f, 0.33f},
{15.0f, 0.48f},
{16.0f, 0.62f},
{17.0f, 0.77f},
{18.0f, 0.9f},
{19.0f, 1.0f}}};
struct HeroLocomotion {
  float enabled;
  float cellSize;
  float baseline;
  float sourceScale;
  float renderSize;
  float strideLength;
  float acceleration;
  float braking;
};
inline constexpr HeroLocomotion heroLocomotion = {1.0f, 160.0f, 156.0f, 0.405f, 100.0f, 88.0f, 1600.0f, 2000.0f};
struct HeroRunMuzzles {
  float x;
  float height;
};
inline constexpr std::array<HeroRunMuzzles, 8> heroRunMuzzles = {{{130.0f, 186.0f},
{135.0f, 192.0f},
{130.0f, 192.0f},
{128.0f, 204.0f},
{129.0f, 197.0f},
{126.0f, 194.0f},
{131.0f, 194.0f},
{118.0f, 203.0f}}};
struct IronlineReview {
  float width;
  float roofY;
  float roofFraction;
  float bridgeStart;
  float bridgeEnd;
  float bridgeY;
  float heroStart;
  float firstGuard;
  float secondGuard;
  float exitX;
  float travelSpeed;
  float mountainDepth;
  float mountainWidth;
  float mountainY;
  float forestDepth;
  float forestWidth;
  float forestY;
  float forestAlpha;
  float fogSpeed;
  float fogAlpha;
  float fogY;
  uint32_t fogColor;
  float windCount;
  float windSpeed;
  uint32_t windColor;
  float cameraAnchor;
  float cameraResponse;
  float cameraMaxSpeed;
  float leadResponse;
};
inline constexpr IronlineReview ironlineReview = {720.0f, 132.0f, 0.273f, 335.0f, 394.0f, 148.7f, 145.0f, 297.0f, 610.0f, 685.0f, 155.0f, 0.055f, 1050.0f, -65.0f, 0.48f, 650.0f, 24.0f, 190.0f, 21.0f, 33.0f, 135.0f, 0x7294ACFFu, 18.0f, 140.0f, 0xA4C8DA50u, 155.0f, 3.2f, 180.0f, 3.5f};
struct ProductionPlates {
  float enabled;
  float sourceFloor;
  float sourceAspect;
};
inline constexpr std::array<ProductionPlates, 6> productionPlates = {{{1.0f, 0.7569546120058566f, 3.0f},
{1.0f, 0.725f, 3.0f},
{0.0f, 0.73f, 3.0f},
{0.0f, 0.778f, 3.0f},
{1.0f, 0.84f, 3.0f},
{1.0f, 0.793f, 3.0f}}};
struct ProductionStructures {
  float deckWidth;
  float postWidth;
  float postInset;
  float postSpacing;
};
inline constexpr ProductionStructures productionStructures = {80.0f, 12.0f, 12.0f, 128.0f};
struct ProductionProps {
  float crateSize;
  float barrelSize;
  float supplySize;
  float beaconSize;
  float workerSize;
  float doorWidth;
  float doorHeight;
  float doorOpenDuration;
  float crateCollisionWidth;
  float crateCollisionHeight;
  float barrelCollisionWidth;
  float barrelCollisionHeight;
};
inline constexpr ProductionProps productionProps = {42.0f, 36.0f, 32.0f, 32.0f, 68.0f, 64.0f, 76.0f, 0.6f, 34.0f, 27.0f, 21.0f, 34.0f};
struct ProductionDepth {
  float nearDepth;
  float floorMargin;
  float stripHeight;
};
inline constexpr ProductionDepth productionDepth = {1.045f, 0.025f, 2.0f};
struct ProductionWeather {
  float map;
  float u0;
  float u1;
  float v0;
  float v1;
  float count;
  float speed;
  float slant;
  float length;
  uint32_t color;
};
inline constexpr std::array<ProductionWeather, 4> productionWeather = {{{0.0f, 0.35f, 1.0f, 0.0f, 0.77f, 68.0f, 0.28f, -0.003f, 0.009f, 0x8EAFC344u},
{1.0f, 0.315f, 0.605f, 0.52f, 0.713f, 58.0f, 0.38f, 0.001f, 0.005f, 0x9EBCC55Au},
{4.0f, 0.0f, 1.0f, 0.0f, 0.83f, 96.0f, 0.055f, -0.002f, 0.0015f, 0xBAD5DE8Au},
{5.0f, 0.63f, 0.97f, 0.05f, 0.79f, 64.0f, 0.22f, -0.003f, 0.008f, 0x8DACB84Au}}};
struct ProductionLights {
  float map;
  float u;
  float v;
  float radius;
  float strength;
  uint32_t color;
};
inline constexpr std::array<ProductionLights, 26> productionLights = {{{1.0f, 0.061f, 0.485f, 130.0f, 0.46f, 0xFFD295FFu},
{1.0f, 0.212f, 0.444f, 115.0f, 0.34f, 0xFFD295FFu},
{1.0f, 0.852f, 0.42f, 180.0f, 0.4f, 0xB0D8CCFFu},
{3.0f, 0.082f, 0.59f, 120.0f, 0.45f, 0xFFD09AFFu},
{3.0f, 0.356f, 0.15f, 240.0f, 0.38f, 0x81CAE7FFu},
{3.0f, 0.815f, 0.57f, 200.0f, 0.65f, 0xFFB578FFu},
{4.0f, 0.145f, 0.664f, 135.0f, 0.5f, 0xFFD89FFFu},
{4.0f, 0.31f, 0.642f, 115.0f, 0.44f, 0xFFD89FFFu},
{4.0f, 0.806f, 0.433f, 175.0f, 0.44f, 0xFFD89FFFu},
{5.0f, 0.146f, 0.574f, 130.0f, 0.4f, 0xFFD7A0FFu},
{5.0f, 0.32f, 0.58f, 135.0f, 0.43f, 0xFFD7A0FFu},
{5.0f, 0.47f, 0.441f, 150.0f, 0.32f, 0xFFE1ADFFu},
{5.0f, 0.925f, 0.3f, 210.0f, 0.32f, 0x93CDE4FFu},
{0.0f, 0.0380859375f, 0.21815519765739386f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.06103515625f, 0.5739385065885798f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.18212890625f, 0.554904831625183f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.19775390625f, 0.24597364568081992f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.3193359375f, 0.3850658857979502f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.3544921875f, 0.664714494875549f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.45166015625f, 0.34260614934114203f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.5419921875f, 0.3850658857979502f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.6572265625f, 0.5578330893118595f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.60400390625f, 0.1698389458272328f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.791015625f, 0.5871156661786238f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.888671875f, 0.5095168374816984f, 120.0f, 0.24f, 0xFFBB7700u},
{0.0f, 0.98974609375f, 0.5534407027818448f, 120.0f, 0.24f, 0xFFBB7700u}}};
struct ForgeTitanCores {
  float x;
  float y;
};
inline constexpr std::array<ForgeTitanCores, 8> forgeTitanCores = {{{131.0f, 225.0f},
{131.0f, 214.0f},
{132.0f, 225.0f},
{130.0f, 197.0f},
{128.0f, 281.0f},
{128.0f, 230.0f},
{150.0f, 266.0f},
{130.0f, 287.0f}}};
struct ForgeTitanPoses {
  float frame;
};
inline constexpr std::array<ForgeTitanPoses, 16> forgeTitanPoses = {{{0.0f},
{1.0f},
{0.0f},
{2.0f},
{0.0f},
{3.0f},
{3.0f},
{4.0f},
{4.0f},
{5.0f},
{5.0f},
{0.0f},
{6.0f},
{6.0f},
{7.0f},
{7.0f}}};
struct ForgeTitan {
  float cellSize;
  float sourceScale;
  float baseline;
  float renderSize;
  float collisionWidth;
  float collisionHeight;
  float muzzleX;
  float muzzleY;
};
inline constexpr ForgeTitan forgeTitan = {320.0f, 0.66f, 308.0f, 208.0f, 150.0f, 155.0f, -23.0f, -6.0f};
struct FoundryHall {
  float sourceFloor;
  float sourceAspect;
  float width;
  float steamSpeed;
  float steamAlpha;
  uint32_t steamColor;
  float emberCount;
  float emberSpeed;
  uint32_t emberColor;
};
inline constexpr FoundryHall foundryHall = {0.778f, 3.0f, 1600.0f, 8.0f, 13.0f, 0x9CBAC4FFu, 20.0f, 16.0f, 0xFFB16C88u};
struct CampaignPresentation {
  float enabled;
  float health;
  float exitHold;
  float cameraPanResponse;
  float cameraMaxSpeed;
  float cameraLeadResponse;
  float bossArenaInset;
};
inline constexpr CampaignPresentation campaignPresentation = {1.0f, 6.0f, 0.8f, 4.0f, 200.0f, 4.0f, 24.0f};
struct Workshop {
  float width;
  float sourceAspect;
  float sourceFloor;
  float cameraLift;
  float heroSize;
  float guardSize;
  float aimSize;
  float climbSize;
  float bodyScale;
  float guardScale;
  float heroStart;
  float guardStart;
  float exitX;
  float ambientGain;
  float foregroundDepth;
  float foregroundAlpha;
};
inline constexpr Workshop workshop = {640.0f, 1.7768331562167907f, 0.71f, 26.0f, 100.0f, 95.0f, 112.0f, 100.0f, 1.65f, 1.6f, 205.0f, 535.0f, 608.0f, 1.18f, 1.035f, 0.15f};
struct WorkshopView {
  float leadResponse;
  float maxCameraSpeed;
  float nearDepth;
  float depthStart;
  float stripHeight;
};
inline constexpr WorkshopView workshopView = {3.5f, 180.0f, 1.08f, 0.75f, 1.0f};
struct WorkshopCamera {
  float establishDuration;
  float establishZoom;
  float trackingZoom;
  float detailZoom;
  float combatZoom;
  float galleryZoom;
  float exitZoom;
  float panResponse;
  float verticalResponse;
  float zoomResponse;
  float maxZoomSpeed;
  float maxVerticalSpeed;
  float idleSpeed;
  float idleDelay;
  float detailStart;
  float detailEnd;
  float detailAnchor;
  float detailLift;
  float combatLift;
  float combatDistance;
  float combatHeight;
  float combatHold;
  float combatSubjectWeight;
  float galleryHeight;
  float galleryFootY;
  float safeLeft;
  float safeRight;
};
inline constexpr WorkshopCamera workshopCamera = {2.0f, 1.0f, 1.015f, 1.075f, 1.035f, 1.0f, 1.065f, 3.2f, 2.4f, 1.5f, 0.035f, 55.0f, 4.0f, 1.3f, 140.0f, 340.0f, 185.0f, -4.0f, -2.0f, 220.0f, 70.0f, 1.25f, 0.45f, 140.0f, 145.0f, 85.0f, 405.0f};
struct WorkshopParallax {
  float depth;
  float width;
  float originX;
  float originY;
  float transmission;
  float chromaThreshold;
  float chromaFeather;
  float darkThreshold;
  float darkFeather;
  float edgeFeather;
  float fogDepth;
  float fogSpeed;
  float fogWave;
  float fogAmplitude;
  float fogY;
  float fogWidth;
  float fogHeight;
  float fogSpacing;
  float fogCount;
  float fogAlpha;
  uint32_t fogColor;
};
inline constexpr WorkshopParallax workshopParallax = {0.22f, 1280.0f, -250.0f, -100.0f, 0.9f, 6.0f, 16.0f, 24.0f, 30.0f, 0.004f, 0.42f, 4.0f, 0.17f, 7.0f, 120.0f, 160.0f, 30.0f, 200.0f, 6.0f, 24.0f, 0x6994A5FFu};
struct WorkshopApertures {
  float x;
  float y;
  float w;
  float h;
};
inline constexpr std::array<WorkshopApertures, 4> workshopApertures = {{{0.278f, 0.058f, 0.084f, 0.156f},
{0.47f, 0.057f, 0.126f, 0.3f},
{0.512f, 0.345f, 0.084f, 0.088f},
{0.632f, 0.058f, 0.102f, 0.44f}}};
struct WorkshopMotion {
  float rainPerPane;
  float rainSpeed;
  float rainLength;
  float rainSlant;
  uint32_t rainColor;
  float terminalSpeed;
  float terminalGain;
  float terminalRadius;
  uint32_t terminalColor;
  float terminalAlpha;
  float rippleSpeed;
  float rippleRadius;
  float rippleAlpha;
};
inline constexpr WorkshopMotion workshopMotion = {9.0f, 0.18f, 0.01f, -0.003f, 0xA6D5E33Cu, 1.7f, 0.11f, 38.0f, 0x88C974FFu, 32.0f, 0.55f, 6.0f, 26.0f};
struct WorkshopPanes {
  float x;
  float y;
  float w;
  float h;
};
inline constexpr std::array<WorkshopPanes, 6> workshopPanes = {{{0.278f, 0.079f, 0.042f, 0.16f},
{0.327f, 0.079f, 0.025f, 0.16f},
{0.48f, 0.063f, 0.053f, 0.253f},
{0.552f, 0.063f, 0.045f, 0.253f},
{0.613f, 0.063f, 0.06f, 0.253f},
{0.687f, 0.063f, 0.046f, 0.253f}}};
struct WorkshopScreens {
  float x;
  float y;
  float w;
  float h;
};
inline constexpr std::array<WorkshopScreens, 2> workshopScreens = {{{0.089f, 0.433f, 0.018f, 0.032f},
{0.453f, 0.49f, 0.033f, 0.048f}}};
struct WorkshopLights {
  float x;
  float y;
  float radius;
  float strength;
  uint32_t color;
  float window;
};
inline constexpr std::array<WorkshopLights, 7> workshopLights = {{{66.0f, 5.0f, 110.0f, 0.4f, 0xFFC28FFFu, 0.0f},
{69.0f, 98.0f, 100.0f, 0.4f, 0xEFA568FFu, 0.0f},
{225.0f, 130.0f, 105.0f, 0.6f, 0xFFD49EFFu, 0.0f},
{270.0f, 158.0f, 65.0f, 0.35f, 0x8DCF83FFu, 0.0f},
{342.0f, 187.0f, 90.0f, 0.55f, 0xFFBC75FFu, 0.0f},
{595.0f, 30.0f, 120.0f, 0.5f, 0xF6AC6CFFu, 0.0f},
{448.0f, 18.0f, 170.0f, 0.4f, 0xA4D7EAFFu, 1.0f}}};
struct HarborBuiltScene {
  float sourceFloor;
  float sourceAspect;
  float doorOpenDuration;
  uint32_t doorInterior;
  uint32_t doorShade;
};
inline constexpr HarborBuiltScene harborBuiltScene = {0.7569546120058566f, 3.0f, 0.6f, 0x05090EFFu, 0x101921FFu};
struct HarborGalleries {
  float u0;
  float u1;
  float v;
};
inline constexpr std::array<HarborGalleries, 3> harborGalleries = {{{0.0f, 0.23876953125f, 0.34699853587115664f},
{0.31640625f, 0.58837890625f, 0.4685212298682284f},
{0.58837890625f, 0.79248046875f, 0.3162518301610542f}}};
struct HarborLadders {
  float u;
  float gallery;
};
inline constexpr std::array<HarborLadders, 6> harborLadders = {{{0.0439453125f, 0.0f},
{0.20849609375f, 0.0f},
{0.33935546875f, 1.0f},
{0.51513671875f, 1.0f},
{0.61279296875f, 2.0f},
{0.7001953125f, 2.0f}}};
struct HarborDoors {
  float u;
  float v;
  float w;
  float h;
};
inline constexpr std::array<HarborDoors, 2> harborDoors = {{{0.1708984375f, 0.5973645680819912f, 0.0224609375f, 0.15666178623718888f},
{0.6396484375f, 0.6002928257686676f, 0.0341796875f, 0.15519765739385066f}}};
} // namespace kh::tuning
